# Generated by Django 3.0.1 on 2020-01-04 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('header', models.TextField(default='', max_length=200)),
                ('tester', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('urgency', models.IntegerField(choices=[('1', 'Most Important'), ('2', 'Priority 2'), ('3', 'Last Priority')])),
                ('types', models.CharField(max_length=100)),
                ('test_object', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=200)),
                ('remarks', models.TextField(default='')),
            ],
        ),
    ]
