# Generated by Django 2.2.4 on 2020-01-31 07:39

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_number',
            field=models.IntegerField(default=UI.models.number, primary_key=True, serialize=False),
        ),
    ]
