# Generated by Django 2.2.4 on 2020-01-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20200131_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='field_name',
            new_name='toggle',
        ),
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.TextField(default='', max_length=100),
        ),
    ]
