# Generated by Django 2.2.4 on 2020-01-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_auto_20200131_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='toggle',
        ),
    ]
