# Generated by Django 2.2.4 on 2020-02-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_remove_post_toggle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hidden',
        ),
    ]
