# Generated by Django 2.2.4 on 2020-02-27 13:32

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_remove_post_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id_number', models.IntegerField(default=UI.models.number, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
